name: Deploy Cloud Functions (test)
on:
  push:
    branches:
      - test
  pull_request:
    types:
      - 'opened'
      - 'synchronize'
      - 'edited'
      - 'reopened'
  workflow_dispatch:

concurrency:
  group: tigers-result-delivery-deploy-test

permissions:
  contents: 'read'
  id-token: 'write'

jobs:
  deploy:
    uses: yananob/cloud-functions-common/.github/workflows/deploy-cloud-functions.yaml@main
    with:
      function_name: 'tigers-result-delivery-test'
      service_account_name: 'cloud-run-functions-deployer'
      wip_pool_name: 'github-actions-pool'
      wip_provider_name: 'github-provider'
      secrets_config: |-
        LINE_TOKENS_N_TARGETS
        FIREBASE_SERVICE_ACCOUNT
      # gcs_source_dir: ./public/
      # gcs_bucket_name: tigers-result-delivery-static
      # gcs_bucket_path: test
      # disable_gcs_cache: true
      deploy_http_trigger: false
      deploy_event_trigger: true
      http_max_instance_count: 1
      memory: '256M'
      http_timeout: '5m'
      event_timeout: '540s'
      environment_variables: |-
        APP_ENV=test
    secrets:
      GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
      GCP_REGION: ${{ secrets.GCP_REGION }}
      GCP_PROJECT_NUMBER: ${{ secrets.GCP_PROJECT_NUMBER }}
